name: Realtime Analytics CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run PySpark unit tests
      run: |
        pytest ./src/pyspark_pipeline/tests || true

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3

    - name: Build Docker images
      run: |
        docker-compose -f docker/docker-compose.yml build || true
